apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: gitops-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: other-pvc
  namespace: gitops-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
